spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
      username: sa
      password: 1234
  jpa:
    show-sql: true
    properties:
      hiberate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect.storage_engine: innodb
  session:
    store-type: jdbc
  h2:
    console:
      enabled: false